### ISSUE TITLE
how can i purchase for this script

### ISSUE THREAD

**Issue by vietanh1104** [thequickcode/quick-code-examples#1]
in readme.md file, you said "When extracting the files you have downloaded after purchasing the script, you will find a folder named: frontend-src.zip", so would u like to tell where i can purchase this script, please

**Comment by thequickcode** [comment]
Thank you for reaching out to us,

You can buy it from our website: https://quickcode.digital 

You can have a look at our demo from: https://demo.quickcode.digital

Let me know if you any other questions,
